### PR TITLE
Provide more verbose diagnostics in klp_tc_exit

### PR DESCRIPTION
**Pull request by lpechacek**
Problems during test setup teardown qualify for a fix too. Provide verbose diagnostics in this phase too so that they can be addressed.

### CODE REVIEW

**Comment by pevik** [comment]
LGTM, thanks!

**Comment by pevik** [comment]
@nicstange FYI

**Review by pevik — APPROVED** [review]

**Comment by pevik** [comment]
@lpechacek Would you please merge this?

**Comment by lpechacek** [comment]
I've been waiting for Nicolai's patches so that I would update the repo in one run. They seem very relevant to me. I'll check with Nicolai.

**Comment by lpechacek** [comment]
I've synced with Nicolai. We agreed on merging this bit first.

**Pull request merged**
